### ISSUE TITLE
Center image without ugly table structure

### ISSUE THREAD

**Issue by DavidGinzberg** [OpenDataDE/OpenDataDe.github.io#7]
Center the page image using just css. eg:

```css
.centered {
  position: fixed;
  top: 50%;
  left: 50%;
  /* bring your own prefixes */
  transform: translate(-50%, -50%);
}
```
